
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hilman Fauzi Rijal
 */
public class GUI extends javax.swing.JFrame {

    private ArrayList<Anggota> anggota = new ArrayList<>();
    private ArrayList<Buku> buku = new ArrayList<>();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginMenu = new javax.swing.JPanel();
        idAdimn = new javax.swing.JTextField();
        passAdmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        MenuDataBuku = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        MenuDataAnggota = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tambahAnggota = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        idAdimn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAdimnActionPerformed(evt);
            }
        });
        idAdimn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idAdimnKeyPressed(evt);
            }
        });

        passAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passAdminActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginMenuLayout = new javax.swing.GroupLayout(LoginMenu);
        LoginMenu.setLayout(LoginMenuLayout);
        LoginMenuLayout.setHorizontalGroup(
            LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginMenuLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(LoginMenuLayout.createSequentialGroup()
                        .addGroup(LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idAdimn)
                            .addComponent(passAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        LoginMenuLayout.setVerticalGroup(
            LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginMenuLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAdimn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        getContentPane().add(LoginMenu, "card2");

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DataAnggota");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Data Buku");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        getContentPane().add(MainMenu, "card3");

        jLabel5.setText("Data Buku");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Judul", "Pengarang", "Penerbit", "Jumlah"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton7.setText("Kembali");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Tambah");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Edit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Hapus");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuDataBukuLayout = new javax.swing.GroupLayout(MenuDataBuku);
        MenuDataBuku.setLayout(MenuDataBukuLayout);
        MenuDataBukuLayout.setHorizontalGroup(
            MenuDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDataBukuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7))
            .addGroup(MenuDataBukuLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(MenuDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDataBukuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(100, 100, 100))
        );
        MenuDataBukuLayout.setVerticalGroup(
            MenuDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDataBukuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addGroup(MenuDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton7))
        );

        getContentPane().add(MenuDataBuku, "card4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "NIM", "Nama", "Masa Berlaku"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Anggota");

        tambahAnggota.setText("Tambah");
        tambahAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAnggotaActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Cari No Anggota");

        javax.swing.GroupLayout MenuDataAnggotaLayout = new javax.swing.GroupLayout(MenuDataAnggota);
        MenuDataAnggota.setLayout(MenuDataAnggotaLayout);
        MenuDataAnggotaLayout.setHorizontalGroup(
            MenuDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDataAnggotaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5))
            .addGroup(MenuDataAnggotaLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(MenuDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuDataAnggotaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335)
                        .addComponent(tambahAnggota))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuDataAnggotaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        MenuDataAnggotaLayout.setVerticalGroup(
            MenuDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDataAnggotaLayout.createSequentialGroup()
                .addGroup(MenuDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuDataAnggotaLayout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addComponent(tambahAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(MenuDataAnggotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton5))
        );

        getContentPane().add(MenuDataAnggota, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Admin adm = new Admin();
        boolean passLogin = false;
        if (adm.adminLogin(idAdimn.getText(), passAdmin.getText())) {
            MainMenu.setVisible(true);
            LoginMenu.setVisible(false);
            idAdimn.setText("");
            passAdmin.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void idAdimnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idAdimnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAdimnKeyPressed

    private void idAdimnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAdimnActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_idAdimnActionPerformed

    private void passAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passAdminActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_passAdminActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginMenu.setVisible(true);
        MainMenu.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void clearTable(DefaultTableModel model) {
        model.setRowCount(0);
    }
    private void tambahAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAnggotaActionPerformed
        // TODO add your handling code here:
        tambahAnggota tambah = new tambahAnggota(this, true);
        tambah.setVisible(true);
        if (tambah.getAng() != null) {
            anggota.add(tambah.getAng());
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        clearTable(model);
        String tanggal = anggota.get(anggota.size() - 1).getMassaBerlaku().getDate() + "-" + (anggota.get(anggota.size() - 1).getMassaBerlaku().getMonth() + 1) + "-" + (anggota.get(anggota.size() - 1).getMassaBerlaku().getYear() + 1900);
        for (int i = 0; i < anggota.size(); i++) {
            model.addRow(new Object[]{anggota.get(i).getNo(), anggota.get(i).getNim(), anggota.get(i).getNama(), tanggal});
        }
    }//GEN-LAST:event_tambahAnggotaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainMenu.setVisible(false);
        MenuDataAnggota.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MainMenu.setVisible(true);
        MenuDataAnggota.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here: 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        clearTable(model);
        String tanggal = "";
        for (int i = 0; i < anggota.size(); i++) {
            if (anggota.get(i).getNo().contains(jTextField1.getText())) {
                tanggal = anggota.get(anggota.size() - 1).getMassaBerlaku().getDate() + "-" + (anggota.get(anggota.size() - 1).getMassaBerlaku().getMonth() + 1) + "-" + (anggota.get(anggota.size() - 1).getMassaBerlaku().getYear() + 1900);
                model.addRow(new Object[]{anggota.get(i).getNo(), anggota.get(i).getNim(), anggota.get(i).getNama(), tanggal});
            }
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainMenu.setVisible(false);
        MenuDataBuku.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MainMenu.setVisible(true);
        MenuDataBuku.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        KelolaBuku tambah = new KelolaBuku(this, true, 1, null);
        tambah.setVisible(true);
        if (tambah.getBuku() != null) {
            buku.add(tambah.getBuku());
        }
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        clearTable(model);
        for (int i = 0; i < buku.size(); i++) {
            model.addRow(new Object[]{buku.get(i).getKode(), buku.get(i).getJudul(), buku.get(i).getPengarang(), buku.get(i).getPenerbit(), buku.get(i).getJumlah()});
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        int ubah = 0;
        for (int i = 0; i < buku.size(); i++) {
            if (jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString().equals(buku.get(i).getKode())) {
                ubah = i;
                break;
            }
        }
        KelolaBuku edit = new KelolaBuku(this, true, 2, (new Buku(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString(),
                jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString(),
                jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString(),
                jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString(),
                Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString()))));
        edit.setVisible(true);
        buku.set(ubah, edit.getBuku());
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        clearTable(model);
        for (int i = 0; i < buku.size(); i++) {
            model.addRow(new Object[]{buku.get(i).getKode(), buku.get(i).getJudul(), buku.get(i).getPengarang(), buku.get(i).getPenerbit(), buku.get(i).getJumlah()});
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int hapus = -1;
        for (int i = 0; i < buku.size(); i++) {
            if (jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString().equals(buku.get(i).getKode())) {
                hapus = i;
                break;
            }
        }
        buku.remove(hapus);
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        clearTable(model);
        for (int i = 0; i < buku.size(); i++) {
            model.addRow(new Object[]{buku.get(i).getKode(), buku.get(i).getJudul(), buku.get(i).getPengarang(), buku.get(i).getPenerbit(), buku.get(i).getJumlah()});
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginMenu;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MenuDataAnggota;
    private javax.swing.JPanel MenuDataBuku;
    private javax.swing.JTextField idAdimn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField passAdmin;
    private javax.swing.JButton tambahAnggota;
    // End of variables declaration//GEN-END:variables
}
